version: '3.8'

services:
  frontend:
    image: sterks/dental_clinic-frontend:latest
    platform: linux/amd64
    restart: unless-stopped
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`ravnovesie-dent.ru`) || Host(`www.ravnovesie-dent.ru`) || Host(`ravnovesije.ru`) || Host(`www.ravnovesije.ru`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.frontend-http.rule=Host(`ravnovesie-dent.ru`) || Host(`www.ravnovesie-dent.ru`) || Host(`ravnovesije.ru`) || Host(`www.ravnovesije.ru`)"
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.routers.frontend-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  traefik:
    image: traefik:v3.4.1
    platform: linux/amd64
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/acme.json:/acme.json:rw
    restart: unless-stopped
    networks:
      - app-network
    labels:
      - "traefik.enable=true"

networks:
  app-network:
    driver: bridge