entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
certificatesResolvers:
  letsencrypt:
    acme:
      email: "runov.denis@yandex.ru"
      storage: /acme.json
      httpChallenge:
        entryPoint: web
api:
  dashboard: true
log:
  level: DEBUG